# Preparación de datos

1. Integración de los datos
2. Eliminar variables irrelevantes y redundantes matemáticamente
3. Descripción estadística de los datos
4. Limpieza de datos atípicos-errores
5. Limpieza de datos nulos
6. Transformaciones (normalización y creación de dummies)

In [ ]:
#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

# 1. Integración de Datos

In [ ]:
# Se cargan los datos
data = pd.read_excel("DatosEnergiasRenovables.xlsx",sheet_name='data')
data.head()

,Country,Region,Year,Petróleo_t,Gas Natural_t,Carbón_t,Energía Nuclear_t,Energía Hidroeléctrica_t,Energías Renovables_t,Energías Renovables_t+1,Nivel transicion energetica_t+1
0,Canada,North America,2022,4.306535,4.457286,0.385116,0.780253,3.732924,0.636991,0.676281,"Medio_0,51-5"
1,Mexico,North America,2022,3.774268,3.274093,0.244213,0.097717,0.333744,0.459067,0.537013,"Medio_0,51-5"
2,US,North America,2022,35.750114,31.665119,9.910711,7.314550,2.358374,8.416627,8.779252,Alto_5
3,Argentina,Cent. America,2022,1.482501,1.650702,0.053610,0.067271,0.213708,0.237979,0.238107,Bajo_0.0-0.5
4,Brazil,Cent. America,2022,5.006519,1.151554,0.585582,0.131125,4.008753,2.552388,2.974078,"Medio_0,51-5"

# 2. Eliminar variables irrelevantes y redundantes
* Irrelevantes: cedulas, ids, nombres, telefonos, direcciones, códigos.
* Redundantes: validación por fórmula matemática que están repetidas

# 3. Descripción estadística

**Variables numéricas**

**Variables categóricas** (value_counts())

**Perfilado de datos**

In [ ]:
!pip install ydata-profiling

from ydata_profiling import ProfileReport

profile_data=ProfileReport(data, minimal=True) # minimal=True
profile_data

In [ ]:
#Guardamos en html el perfilado de datos
profile_data.to_file(output_file="output.html")

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

# 4. Limpieza de datos atípicos-errores

Los boxplots identifican valores extremos, pero la decisión de eliminarlos debe apoyarse en el conocimiento del dominio.

In [ ]:
data.describe()

,Petróleo_t,Gas Natural_t,Carbón_t,Energía Nuclear_t,Energía Hidroeléctrica_t,Energías Renovables_t,Energías Renovables_t+1
count,137.000000,136.000000,132.000000,103.000000,124.000000,136.000000,137.000000
mean,2.634698,2.053200,2.416212,0.476762,0.615265,0.616437,0.688927
std,5.585882,4.476663,10.979144,1.214286,1.673883,1.786415,2.067842
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.451115,0.260963,0.050755,0.000000,0.027252,0.021918,0.025183
50%,0.990510,0.900801,0.163186,0.090965,0.153277,0.113171,0.115973
75%,2.557012,1.820363,0.948623,0.396094,0.418519,0.456802,0.515049
max,35.750114,31.665119,87.832008,7.418466,12.246048,13.370720,16.134484

El boxplot identifica a China como un valor atípico estadístico debido a su enorme consumo de carbón. Sin embargo, al revisar el contexto energético se concluye que no es un error de calidad sino una observación válida que representa la realidad del sistema energético mundia

In [ ]:
#Se asigna valor nulo a los atípicos

data.loc[data["Carbón_t"]>100, "Carbón_t"]=np.nan #data.loc[filas, col]
data.describe()

,Petróleo_t,Gas Natural_t,Carbón_t,Energía Nuclear_t,Energía Hidroeléctrica_t,Energías Renovables_t,Energías Renovables_t+1
count,137.000000,136.000000,132.000000,103.000000,124.000000,136.000000,137.000000
mean,2.634698,2.053200,2.416212,0.476762,0.615265,0.616437,0.688927
std,5.585882,4.476663,10.979144,1.214286,1.673883,1.786415,2.067842
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.451115,0.260963,0.050755,0.000000,0.027252,0.021918,0.025183
50%,0.990510,0.900801,0.163186,0.090965,0.153277,0.113171,0.115973
75%,2.557012,1.820363,0.948623,0.396094,0.418519,0.456802,0.515049
max,35.750114,31.665119,87.832008,7.418466,12.246048,13.370720,16.134484

# **5. Limpieza de datos nulos: Imputación**

Estrategia:
* Eliminar columnas con mas de 15%-20% de nulos
* Imputar por media, moda, mediana, vecinos cercanos. No se puede imputar más allá del 15% de los datos.


* Carbón_t has 5 (3.6%) missing values
* Energía Nuclear_t has 34 (24.8%) missing values
* Energía Hidroeléctrica_t has 13 (9.5%) missing values

In [ ]:
#Energía Nuclear_t tiene más del 15% de nulos, por lo tanto se elimina
data = data.drop(columns='Energía Nuclear_t')
data.head()

,Region,Year,Petróleo_t,Gas Natural_t,Carbón_t,Energía Hidroeléctrica_t,Energías Renovables_t,Energías Renovables_t+1,Nivel transicion energetica_t+1
0,North America,2022,4.306535,4.457286,0.385116,3.732924,0.636991,0.676281,"Medio_0,51-5"
1,North America,2022,3.774268,3.274093,0.244213,0.333744,0.459067,0.537013,"Medio_0,51-5"
2,North America,2022,35.750114,31.665119,9.910711,2.358374,8.416627,8.779252,Alto_5
3,Cent. America,2022,1.482501,1.650702,0.053610,0.213708,0.237979,0.238107,Bajo_0.0-0.5
4,Cent. America,2022,5.006519,1.151554,0.585582,4.008753,2.552388,2.974078,"Medio_0,51-5"

In [ ]:
8#Limpieza de datos nulos: Imputación por la media y moda
from sklearn.impute import SimpleImputer

#Imputacion de variables numéricas: media, mediana
imputar_media = ['Gas Natural_t','Carbón_t','Energía Hidroeléctrica_t','Energías Renovables_t']
ImpNumeros = SimpleImputer(missing_values=np.nan, strategy='mean')
data[imputar_media] = ImpNumeros.fit_transform(data[imputar_media])

#Imputacion de variables categóricas: moda
imputar_moda = ['Region']
ImpCategorias = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
data[imputar_moda] = ImpCategorias.fit_transform(data[imputar_moda])

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 9 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Region                           137 non-null    object
 1   Year                             137 non-null    category
 2   Petróleo_t                       137 non-null    float64
 3   Gas Natural_t                    137 non-null    float64
 4   Carbón_t                         137 non-null    float64
 5   Energía Hidroeléctrica_t         137 non-null    float64
 6   Energías Renovables_t            137 non-null    float64
 7   Energías Renovables_t+1          137 non-null    float64
 8   Nivel transicion energetica_t+1  137 non-null    category
dtypes: category(2), float64(6), object(1)
memory usage: 8.1+ KB

In [ ]:
#Valores de la imputación
print(ImpNumeros.statistics_) #['Gas Natural_t','Carbón_t','Energía Hidroeléctrica_t','Energías Renovables_t']
print(ImpCategorias.statistics_) #['Region']

[2.05320048 2.4162115  0.61526466 0.61643719]
['Europe']

In [ ]:
#Guardamos los datos limpios
data.to_excel('./datos_limpios.xlsx')

# 9. Transformaciones

Se sugiere realizar estas operaciones en el notebook donde se realice la creación de los modelos:
- Normalizar las variables numéricas
- Crear dummies

In [ ]:
data.head()

,Region,Year,Petróleo_t,Gas Natural_t,Carbón_t,Energía Hidroeléctrica_t,Energías Renovables_t,Energías Renovables_t+1,Nivel transicion energetica_t+1
0,North America,2022,4.306535,4.457286,0.385116,3.732924,0.636991,0.676281,"Medio_0,51-5"
1,North America,2022,3.774268,3.274093,0.244213,0.333744,0.459067,0.537013,"Medio_0,51-5"
2,North America,2022,35.750114,31.665119,9.910711,2.358374,8.416627,8.779252,Alto_5
3,Cent. America,2022,1.482501,1.650702,0.053610,0.213708,0.237979,0.238107,Bajo_0.0-0.5
4,Cent. America,2022,5.006519,1.151554,0.585582,4.008753,2.552388,2.974078,"Medio_0,51-5"

In [ ]:
#Normalización: Sólo para variables numéricas (no dummies)
from sklearn.preprocessing import MinMaxScaler

variables_predictoras_numericas=['Petróleo_t','Gas Natural_t','Carbón_t','Energía Hidroeléctrica_t','Energías Renovables_t']

min_max_scaler = MinMaxScaler()
data[variables_predictoras_numericas] = min_max_scaler.fit_transform(data[variables_predictoras_numericas])
data.head()

,Region,Year,Petróleo_t,Gas Natural_t,Carbón_t,Energía Hidroeléctrica_t,Energías Renovables_t,Energías Renovables_t+1,Nivel transicion energetica_t+1
0,North America,2022,0.120462,0.140763,0.004385,0.304827,0.047641,0.676281,"Medio_0,51-5"
1,North America,2022,0.105574,0.103397,0.002780,0.027253,0.034334,0.537013,"Medio_0,51-5"
2,North America,2022,1.000000,1.000000,0.112837,0.192582,0.629482,8.779252,Alto_5
3,Cent. America,2022,0.041468,0.052130,0.000610,0.017451,0.017799,0.238107,Bajo_0.0-0.5
4,Cent. America,2022,0.140042,0.036367,0.006667,0.327351,0.190894,2.974078,"Medio_0,51-5"

In [ ]:
data.describe()

,Petróleo_t,Gas Natural_t,Carbón_t,Energía Hidroeléctrica_t,Energías Renovables_t,Energías Renovables_t+1
count,137.000000,137.000000,137.000000,137.000000,137.000000,137.000000
mean,0.073698,0.064841,0.027509,0.050242,0.046104,0.688927
std,0.156248,0.140854,0.122682,0.129991,0.133114,2.067842
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.012619,0.008260,0.000593,0.002669,0.001652,0.025183
50%,0.027706,0.030988,0.002259,0.015121,0.008554,0.115973
75%,0.071525,0.058262,0.015985,0.050242,0.034334,0.515049
max,1.000000,1.000000,1.000000,1.000000,1.000000,16.134484

In [ ]:
#Creación de dummies a las variables categóricas

#Variables categóricas con 2 categorías -> Borramos una dummy
data = pd.get_dummies(data, columns=['Year'], drop_first=, dtype=int)

#Variables categóricas con más de 2 categorías -> No borramos
data = pd.get_dummies(data, columns=['Region'], drop_first=, dtype=int)
data.head()

,Petróleo_t,Gas Natural_t,Carbón_t,Energía Hidroeléctrica_t,Energías Renovables_t,Energías Renovables_t+1,Nivel transicion energetica_t+1,Year_2022,Region_Africa,Region_Asia Pacific,Region_CIS,Region_Cent. America,Region_Europe,Region_Middle East,Region_North America
0,4.306535,4.457286,0.385116,3.732924,0.636991,0.676281,"Medio_0,51-5",1,0,0,0,0,0,0,1
1,3.774268,3.274093,0.244213,0.333744,0.459067,0.537013,"Medio_0,51-5",1,0,0,0,0,0,0,1
2,35.750114,31.665119,9.910711,2.358374,8.416627,8.779252,Alto_5,1,0,0,0,0,0,0,1
3,1.482501,1.650702,0.053610,0.213708,0.237979,0.238107,Bajo_0.0-0.5,1,0,0,0,1,0,0,0
4,5.006519,1.151554,0.585582,4.008753,2.552388,2.974078,"Medio_0,51-5",1,0,0,0,1,0,0,0